# Generated by Django 4.0.3 on 2022-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('product_id', models.CharField(max_length=120, null=True)),
                ('org_id', models.CharField(max_length=120, null=True)),
                ('qty', models.IntegerField()),
                ('exp_time', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.CharField(max_length=120, unique=True)),
                ('org_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200, null=True)),
                ('exp_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
    ]
