# Generated by Django 4.0.3 on 2022-05-16 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_storebuyer'),
        ('store', '0002_products_price_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organisation'),
        ),
    ]
