# Generated by Django 4.0.3 on 2022-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='single_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
